name: Heartbeat Auto Commit

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # ✅ Para may commit rights

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git Config
        run: |
    mkdir -p logs
          git config --global user.name "nosense00-bot"
          git config --global user.email "bot@users.noreply.github.com"

      - name: Create random update
        run: |
    mkdir -p logs
          echo "$(date) - Heartbeat ping" >> logs/activity-log.txt
          echo $RANDOM >> logs/activity-log.txt

      - name: Commit changes
        run: |
    mkdir -p logs
          git add .
          git commit -m "chore: heartbeat auto-ping $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes" || true || echo "No changes, skipping commit"

      - name: Push changes
        run: git push origin main


